---
- name: Slurmctld service needs to run
  service:
    name: slurmctld
    state: started

- name: Turn on elasticsearch jobcompletion plugin
  lineinfile:
    dest: /etc/slurm/slurm.conf
    line: "JobCompType=jobcomp/elasticsearch"
    regexp: "^#?JobCompType="
  notify: "restart slurmctld"
- name: Specify elasticsearch server
  lineinfile:
    dest: /etc/slurm/slurm.conf
    line: "JobCompLoc=http://{{ elasticsearch.ip }}:{{ elasticsearch.port }}"
    regexp: "^#?JobCompLoc="
  notify: "restart slurmctld"
